import React from 'react';
import './globals.css';
import { karla } from './font';
import { Metadata } from 'next';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={karla.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
