import { karla } from '../font';
import clsx from 'clsx';
import * as React from 'react';
import prisma from '@/services/prisma';
import { Metadata } from 'next';
import { HeaderOther } from '@/components/common/shop/header/headerOther';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function ShopLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const categories = await prisma.category.findMany({
    select: { name: true, id: true },
  });

  return (
    <section
      className={clsx(karla.className, 'relative flex h-full w-full flex-col')}
    >
      <HeaderOther categories={categories} />
      {children}
    </section>
  );
}
